// 診断画面と結果一覧で共通使用する拳銃データ
const guns = [
  {
    name: "Colt Python",
    jaName: "コルト・パイソン",
    image: "https://upload.wikimedia.org/wikipedia/commons/0/06/ColtPython.jpg",
    imageSource: "https://commons.wikimedia.org/wiki/File:ColtPython.jpg",
    imageCredit: "Sf46",
    imageLicense: "Public Domain",
    imageNote: "",
    traits: {
      style: 5, practical: 2, classic: 5, modern: 1, elegant: 5,
      rugged: 2.5, unique: 3, professional: 1, mechanical: 4, compact: 1,
      experimental: 0.5,
    },
    tags: ["クラシック", "高級感", "存在感"],
    copy: "古典的な美しさと強い存在感を持つ人物に似合う一丁。",
    detail: "端正で華やかな外観を持つリボルバーです。実用品としての無難さより、完成された造形や威厳を重視するキャラクターに向きます。落ち着きがありながら、持ち物には明確なこだわりがある人物と相性がよいでしょう。",
  },
  {
    name: "Beretta 92FS Inox",
    jaName: "ベレッタ 92FS イノックス",
    image: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Beretta_92_FSi.JPG",
    imageSource: "https://commons.wikimedia.org/wiki/File:Beretta_92_FSi.JPG",
    imageCredit: "Prnrm",
    imageLicense: "CC BY-SA 3.0",
    imageLicenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    imageNote: "",
    traits: {
      style: 5, practical: 3.5, classic: 3, modern: 3, elegant: 5,
      rugged: 1, unique: 2.5, professional: 3.5, mechanical: 4, compact: 1,
      experimental: 0.5,
    },
    tags: ["華やか", "洗練", "存在感"],
    copy: "実用性を保ちながら、隠しきれない華やかさがある人物向け。",
    detail: "92FSの端正さに、さらに視覚的な存在感を足したタイプです。衣装や小物まで含めて見せ方を意識するキャラクターに似合います。",
  },
  {
    name: "Glock 17",
    jaName: "グロック 17",
    image: "https://upload.wikimedia.org/wikipedia/commons/4/45/Glock_17.jpg",
    imageSource: "https://commons.wikimedia.org/wiki/File:Glock_17.jpg",
    imageCredit: "Jmajonis",
    imageLicense: "CC BY-SA 3.0",
    imageLicenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    imageNote: "",
    traits: {
      style: 1, practical: 5, classic: 1, modern: 5, elegant: 1,
      rugged: 3, unique: 0.5, professional: 5, mechanical: 1, compact: 2.5,
      experimental: 0,
    },
    tags: ["合理的", "現代的", "実務派"],
    copy: "道具は道具、と割り切れる合理主義者に似合います。",
    detail: "装飾性よりも簡潔さと実務的な印象が強いタイプです。目立つことに価値を置かず、必要な仕事を確実にこなすキャラクターと相性がよいでしょう。",
  },
  {
    name: "H&K USP",
    jaName: "H&K USP",
    image: "https://upload.wikimedia.org/wikipedia/commons/d/dd/First-year_H%26K_USP_9mm_%2832415150000%29_modified.png",
    imageSource: "https://commons.wikimedia.org/wiki/File:First-year_H%26K_USP_9mm_(32415150000)_modified.png",
    imageCredit: "lifesizepotato / JayCoop",
    imageLicense: "CC0 1.0",
    imageLicenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    imageNote: "",
    traits: {
      style: 2, practical: 5, classic: 2, modern: 4, elegant: 1,
      rugged: 5, unique: 1.5, professional: 5, mechanical: 3, compact: 1,
      experimental: 0.5,
    },
    tags: ["無骨", "堅実", "プロフェッショナル"],
    copy: "無駄に飾らず、仕事道具としての説得力を重視する人物向け。",
    detail: "大ぶりで無骨な印象があり、華美ではありません。冷静な工作員、警備要員、寡黙なプロなど、道具に信頼性と確かな存在感を求めるキャラクターに向きます。",
  },
  {
    name: "SIG Sauer P226",
    jaName: "SIG ザウエル P226",
    image: "https://upload.wikimedia.org/wikipedia/commons/3/36/Sig_Sauer_P226.jpg",
    imageSource: "https://commons.wikimedia.org/wiki/File:Sig_Sauer_P226.jpg",
    imageCredit: "Bruce Varner (Btvarner)",
    imageLicense: "CC BY-SA 3.0",
    imageLicenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    imageNote: "",
    traits: {
      style: 3, practical: 5, classic: 3, modern: 3.5, elegant: 4,
      rugged: 3, unique: 1.5, professional: 5, mechanical: 3, compact: 1,
      experimental: 0.5,
    },
    tags: ["正統派", "堅実", "プロ仕様"],
    copy: "実績ある正統派の道具を、きちんと選ぶ人物に似合います。",
    detail: "実務的な説得力が強い一方で、無骨一辺倒ではないタイプです。職人気質、高い訓練度、落ち着いた自信を持つキャラクターに合わせやすいでしょう。",
  },
  {
    name: "Walther P99",
    jaName: "ワルサー P99",
    image: "https://upload.wikimedia.org/wikipedia/commons/4/44/Walther_P99.jpg",
    imageSource: "https://commons.wikimedia.org/wiki/File:Walther_P99.jpg",
    imageCredit: "U.S. Bureau of Alcohol, Tobacco, Firearms and Explosives",
    imageLicense: "Public Domain",
    imageNote: "",
    traits: {
      style: 4, practical: 4, classic: 1, modern: 5, elegant: 4,
      rugged: 2, unique: 3, professional: 4, mechanical: 2.5, compact: 2.5,
      experimental: 1.5,
    },
    tags: ["スマート", "現代的", "独自設計"],
    copy: "端正なのに少し変わっている、知的な人物に似合うタイプ。",
    detail: "現代的で滑らかな雰囲気を持ちつつ、定番一辺倒ではない個性があります。合理的なのに趣味性もあり、知的で少し癖のあるキャラクターに向いています。",
  },
  {
    name: "CZ 75",
    jaName: "CZ 75",
    image: "https://upload.wikimedia.org/wikipedia/commons/8/81/Cz75.jpg",
    imageSource: "https://commons.wikimedia.org/wiki/File:Cz75.jpg",
    imageCredit: "Jason9811",
    imageLicense: "CC BY-SA 2.5",
    imageLicenseUrl: "https://creativecommons.org/licenses/by-sa/2.5/",
    imageNote: "",
    traits: {
      style: 4, practical: 4.5, classic: 4, modern: 2, elegant: 3.5,
      rugged: 2, unique: 2.5, professional: 3, mechanical: 5, compact: 2,
      experimental: 1,
    },
    tags: ["機械美", "実用派", "通好み"],
    copy: "目立つためではなく、自分の趣味で良いものを選ぶ人物向け。",
    detail: "古典的な美しさと機械的な魅力がありながら、過剰な自己主張はしません。道具に詳しい人物、静かなこだわりを持つ人物に似合います。",
  },
  {
    name: "M1911",
    jaName: "M1911",
    image: "https://upload.wikimedia.org/wikipedia/commons/4/4f/M1911_pistol.jpg",
    imageSource: "https://commons.wikimedia.org/wiki/File:M1911_pistol.jpg",
    imageCredit: "Ecrelin",
    imageLicense: "CC0 1.0",
    imageLicenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    imageNote: "",
    traits: {
      style: 4.5, practical: 3.5, classic: 5, modern: 1, elegant: 3.5,
      rugged: 5, unique: 2.5, professional: 3.5, mechanical: 5, compact: 1,
      experimental: 0.5,
    },
    tags: ["古典", "様式美", "強いこだわり"],
    copy: "古いものを古いからこそ愛せる、信念の強い人物に似合います。",
    detail: "歴史性と象徴性が非常に強いタイプです。最新性よりも伝統、手触り、形式を重視するキャラクターに向きます。",
  },
  {
    name: "Browning Hi-Power",
    jaName: "ブローニング・ハイパワー",
    image: "https://upload.wikimedia.org/wikipedia/commons/e/e3/FN_Hi_Power.jpg",
    imageSource: "https://commons.wikimedia.org/wiki/File:FN_Hi_Power.jpg",
    imageCredit: "U.S. Bureau of Alcohol, Tobacco, Firearms and Explosives",
    imageLicense: "Public Domain",
    imageNote: "",
    traits: {
      style: 4, practical: 4, classic: 5, modern: 1.5, elegant: 5,
      rugged: 2, unique: 1.5, professional: 4, mechanical: 3.5, compact: 2,
      experimental: 0.5,
    },
    tags: ["古典", "端正", "実績"],
    copy: "クラシックが好きでも、過剰な主張は好まない人物に。",
    detail: "古典的な輪郭と端正さがあり、落ち着いた印象です。伝統を好みながらも、大げさな演出を必要としないキャラクターに合わせやすいでしょう。",
  },
  {
    name: "Walther PPK",
    jaName: "ワルサー PPK",
    image: "https://upload.wikimedia.org/wikipedia/commons/2/28/Das_walther_ppk.jpg",
    imageSource: "https://commons.wikimedia.org/wiki/File:Das_walther_ppk.jpg",
    imageCredit: "Jaikuma",
    imageLicense: "CC BY-SA 3.0",
    imageLicenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    imageNote: "",
    traits: {
      style: 4, practical: 3, classic: 5, modern: 1, elegant: 5,
      rugged: 1, unique: 2, professional: 2.5, mechanical: 3, compact: 5,
      experimental: 0.5,
    },
    tags: ["小型", "クラシック", "洗練"],
    copy: "目立ちすぎず、古典的な洗練を持つ人物に似合います。",
    detail: "小型で端正なシルエットを持つクラシックな一丁です。派手さよりも品のある存在感や携帯しやすいサイズ感を好むキャラクターに向きます。落ち着いた服装や、控えめながら持ち物にはこだわる人物とも相性がよいでしょう。",
  },
  {
    name: "Desert Eagle",
    jaName: "デザートイーグル",
    image: "https://images.unsplash.com/photo-1681680020165-6b6f7af3c6ce?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=60&w=3000",
    imageSource: "https://unsplash.com/photos/a-close-up-of-a-gun-on-a-black-surface-MsdDbOUTiu4",
    imageSourceName: "Unsplash",
    imageCredit: "Thomas Tucker",
    imageLicense: "Unsplash License",
    imageLicenseUrl: "https://unsplash.com/license",
    imageNote: "",
    traits: {
      style: 5, practical: 0.5, classic: 2, modern: 2.5, elegant: 1,
      rugged: 5, unique: 5, professional: 0.5, mechanical: 5, compact: 0,
      experimental: 2.5,
    },
    tags: ["強烈", "派手", "ロマン"],
    copy: "合理性よりも存在感。持つだけで画面の印象を大きく変える人物向け。",
    detail: "視覚的なインパクトが非常に強く、実務的な無難さよりキャラクター性を前面に出すタイプです。派手好き、怪力、誇張された悪役などに向きます。",
  },
  {
    name: "FN Five-seveN",
    jaName: "FN ファイブセブン",
    image: "https://upload.wikimedia.org/wikipedia/commons/5/5a/FN_Five_Seven.jpg",
    imageSource: "https://commons.wikimedia.org/wiki/File:FN_Five_Seven.jpg",
    imageCredit: "U.S. Bureau of Alcohol, Tobacco, Firearms and Explosives",
    imageLicense: "Public Domain",
    imageNote: "",
    traits: {
      style: 3, practical: 4, classic: 0.5, modern: 5, elegant: 2,
      rugged: 2, unique: 4, professional: 4, mechanical: 2.5, compact: 2,
      experimental: 2,
    },
    tags: ["現代的", "軽量", "特殊"],
    copy: "普通ではない理由を、きちんと説明できる人物に似合います。",
    detail: "現代的で独特な立ち位置を持つため、単なる奇抜さよりも『選ぶ理由がある』キャラクターに向きます。専門知識のある人物や合理的な変わり者と好相性です。",
  },
  {
    name: "Ruger P85",
    jaName: "ルガー P85",
    image: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Ruger_P89.jpg",
    imageSource: "https://commons.wikimedia.org/wiki/File:Ruger_P89.jpg",
    imageCredit: "U.S. Bureau of Alcohol, Tobacco, Firearms and Explosives",
    imageLicense: "Public Domain",
    imageNote: "※ P85の同系列であるRuger P89の参考画像",
    traits: {
      style: 1, practical: 5, classic: 3, modern: 2, elegant: 1,
      rugged: 5, unique: 1, professional: 3.5, mechanical: 3, compact: 1.5,
      experimental: 0.5,
    },
    tags: ["地味", "頑丈", "実用品"],
    copy: "華やかさより、頑丈さと実直さを好む人物向け。",
    detail: "洗練された見栄えを競うというより、無骨で実直な印象を持つタイプです。実用品に妙な愛着を持つ人物や、飾らない性格のキャラクターに似合います。",
  },
  {
    name: "Kel-Tec P50",
    jaName: "ケルテック P50",
    image: "https://upload.wikimedia.org/wikipedia/commons/3/33/Lel-Kek_P50.jpg",
    imageSource: "https://commons.wikimedia.org/wiki/File:Lel-Kek_P50.jpg",
    imageCredit: "east718",
    imageLicense: "CC BY-SA 4.0",
    imageLicenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    imageNote: "※ ブレース、光学照準器、ライト装着個体。Commons上の現行版はHohumによる色調調整あり",
    rare: "modern_oddity",
    traits: {
      style: 4, practical: 1, classic: 0, modern: 5, elegant: 0.5,
      rugged: 2.5, unique: 5, professional: 0.5, mechanical: 5, compact: 0,
      experimental: 5,
    },
    tags: ["異色", "未来的", "変則設計"],
    copy: "普通の拳銃では物足りない、変則設計そのものを楽しめる人物に。",
    detail: "P90系の50発マガジンを横向きに使う独特な構成など、普通の拳銃とは明確に違う設計が特徴です。実用性だけで無難な定番を選ぶ人物より、新しい機構や変則的な構造そのものを面白がれるキャラクターに似合います。",
  },
  {
    name: "Apache Revolver",
    jaName: "アパッチ・リボルバー",
    image: "https://upload.wikimedia.org/wikipedia/commons/2/28/Apache_revolver.jpg",
    imageSource: "https://commons.wikimedia.org/wiki/File:Apache_revolver.jpg",
    imageCredit: "Latente",
    imageLicense: "CC BY-SA 2.0",
    imageLicenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    imageNote: "",
    rare: "antique_oddity",
    traits: {
      style: 4, practical: 0, classic: 5, modern: 0, elegant: 0.5,
      rugged: 3.5, unique: 5, professional: 0, mechanical: 5, compact: 3,
      experimental: 5,
    },
    tags: ["珍品", "古典", "異様な機構"],
    copy: "古い珍品と奇妙な機構を、実用性より面白さで選ぶ人物向け。",
    detail: "通常の拳銃らしさより、歴史的な珍しさや奇妙な構造に価値を感じるキャラクターに似合います。骨董品、収集癖、危うい趣味性を持つ人物なら特に自然です。",
  },
];
